name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Hello World 출력!!
      run: echo Hello, World!
    - name: 디렉토리 출력!!
      run: ls -al
    - name: 파이썬 버전 출력!!
      run: python -V
    - name: 파이썬 실행!!
      run: python test.py

    - name: 파일찾기!!
      run: sudo find / -name 'test.py'

